export const PYTHON_IMAGE = "python:3.8-slim";

//THIS WILL REPRESENT THE HEADER SIZE OF DOCKER STREAM
//DOCKER STREAM HEADER WILL CONTAIN DATA ABOUT TYPE OF STREAM I.E STDOUT/STDERR
//AND THE LENGTH OF DATA
export const DOCKER_STREAM_HEADER_SIZE = 8;
